"""Shared deep-research subsystem for the CultureBotAI fleet.

Owns the provider catalogue, focus-profile validation, deterministic triage,
execution policy, and schema-governed result capture. Each Mech keeps its own
``conf/deep_research_provider.yaml`` focus profile and domain promotion rules;
the method, safety rules, triage contract, and audit record live here.

Nothing in this package performs network access. Values read from recognised
credential environment variables are only checked for non-emptiness and are
never returned, retained, or printed.
"""

from __future__ import annotations

from .policy import (
    COST_TIERS,
    PolicyError,
    authorize,
    plan_stage,
)
from .profile import (
    Focus,
    ProfileError,
    ResearchProfile,
    Stage,
    load_profile,
    load_profile_bytes,
    parse_profile,
)
from .providers import (
    ALIASES,
    ALL_CAPABILITIES,
    AVAILABILITY_EVIDENCE_VERSION,
    BILLING_CLASSES,
    COST_VALUE,
    CREDENTIALS,
    KNOWN_BLOCKED,
    PROVIDER_CATALOGUE_SHA256,
    PROVIDER_CATALOGUE_VERSION,
    PROVIDERS,
    SYNTHESIS_VALUE,
    TIME_VALUE,
    TRIAGE_ALGORITHM_ID,
    TRIAGE_CONTRACT_SHA256,
    TRIAGE_CONTRACT_VERSION,
    AvailabilityError,
    AvailabilityEvidence,
    LocalProbe,
    Provider,
    StaticAvailability,
    StaticProbe,
    SystemProbe,
    canonical_provider,
    credential_status,
    load_availability,
    normalize_allowlist,
    provider_status,
    requires_usage_authorization,
    unknown_providers,
)
from .records import (
    RESEARCH_VERSION,
    ResearchRecordError,
    build_dry_run_result,
    default_research_schema_path,
    load_result,
    new_result_path,
    render_stage_query,
    result_yaml,
    sha256_bytes,
    sha256_text,
    validate_result,
    write_result,
)
from .triage import build_report, rank_stage, recommendable, score

__all__ = [
    "ALIASES",
    "ALL_CAPABILITIES",
    "AVAILABILITY_EVIDENCE_VERSION",
    "BILLING_CLASSES",
    "COST_TIERS",
    "COST_VALUE",
    "CREDENTIALS",
    "KNOWN_BLOCKED",
    "PROVIDERS",
    "PROVIDER_CATALOGUE_SHA256",
    "PROVIDER_CATALOGUE_VERSION",
    "SYNTHESIS_VALUE",
    "TIME_VALUE",
    "TRIAGE_ALGORITHM_ID",
    "TRIAGE_CONTRACT_SHA256",
    "TRIAGE_CONTRACT_VERSION",
    "AvailabilityEvidence",
    "AvailabilityError",
    "Focus",
    "LocalProbe",
    "PolicyError",
    "ProfileError",
    "Provider",
    "RESEARCH_VERSION",
    "ResearchRecordError",
    "ResearchProfile",
    "Stage",
    "StaticAvailability",
    "StaticProbe",
    "SystemProbe",
    "authorize",
    "build_dry_run_result",
    "build_report",
    "canonical_provider",
    "credential_status",
    "default_research_schema_path",
    "load_profile",
    "load_profile_bytes",
    "load_result",
    "load_availability",
    "normalize_allowlist",
    "new_result_path",
    "parse_profile",
    "plan_stage",
    "provider_status",
    "rank_stage",
    "recommendable",
    "render_stage_query",
    "requires_usage_authorization",
    "result_yaml",
    "score",
    "sha256_bytes",
    "sha256_text",
    "unknown_providers",
    "validate_result",
    "write_result",
]
